/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { AccountGenerationRequestDto } from '../models/AccountGenerationRequestDto';
import type { ApiResponseWrapperCompteDto } from '../models/ApiResponseWrapperCompteDto';
import type { ApiResponseWrapperListCompteDto } from '../models/ApiResponseWrapperListCompteDto';
import type { ApiResponseWrapperString } from '../models/ApiResponseWrapperString';
import type { CompteDto } from '../models/CompteDto';
import type { CancelablePromise } from '../core/CancelablePromise';
import { OpenAPI } from '../core/OpenAPI';
import { request as __request } from '../core/request';
export class AccountingComptesService {
    /**
     * Get account by ID
     * @param id
     * @returns ApiResponseWrapperCompteDto OK
     * @throws ApiError
     */
    public static getCompteById(
        id: string,
    ): CancelablePromise<ApiResponseWrapperCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/{id}',
            path: {
                'id': id,
            },
        });
    }
    /**
     * Update an account
     * @param id
     * @param requestBody
     * @returns ApiResponseWrapperCompteDto OK
     * @throws ApiError
     */
    public static updateCompte(
        id: string,
        requestBody: CompteDto,
    ): CancelablePromise<ApiResponseWrapperCompteDto> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/accounting/comptes/{id}',
            path: {
                'id': id,
            },
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Delete an account
     * @param id
     * @returns ApiResponseWrapperString OK
     * @throws ApiError
     */
    public static deleteCompte(
        id: string,
    ): CancelablePromise<ApiResponseWrapperString> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/accounting/comptes/{id}',
            path: {
                'id': id,
            },
        });
    }
    /**
     * List all accounts
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static getAllComptes(): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes',
        });
    }
    /**
     * Create an accounting account
     * @param requestBody
     * @returns ApiResponseWrapperCompteDto OK
     * @throws ApiError
     */
    public static createCompte(
        requestBody: CompteDto,
    ): CancelablePromise<ApiResponseWrapperCompteDto> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/accounting/comptes',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Generate and create an account based on type
     * @param requestBody
     * @returns ApiResponseWrapperCompteDto OK
     * @throws ApiError
     */
    public static createAutoGeneratedAccount(
        requestBody: AccountGenerationRequestDto,
    ): CancelablePromise<ApiResponseWrapperCompteDto> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/accounting/comptes/generate',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Get accounts by type
     * @param type
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static getAccountsByType(
        type: string,
    ): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/type/{type}',
            path: {
                'type': type,
            },
        });
    }
    /**
     * Get all supplier accounts
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static getSupplierAccounts(): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/suppliers',
        });
    }
    /**
     * Search accounts by account number
     * @param noCompte
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static findByNoCompte(
        noCompte: string,
    ): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/search',
            query: {
                'no_compte': noCompte,
            },
        });
    }
    /**
     * Get all client accounts
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static getClientAccounts(): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/clients',
        });
    }
    /**
     * Get all cash accounts
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static getCashAccounts(): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/cash',
        });
    }
    /**
     * Get all bank accounts
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static getBankAccounts(): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/banks',
        });
    }
}
