/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ApiResponseWrapperCompteDto } from '../models/ApiResponseWrapperCompteDto';
import type { ApiResponseWrapperListCompteDto } from '../models/ApiResponseWrapperListCompteDto';
import type { ApiResponseWrapperString } from '../models/ApiResponseWrapperString';
import type { CompteDto } from '../models/CompteDto';
import type { CancelablePromise } from '../core/CancelablePromise';
import { OpenAPI } from '../core/OpenAPI';
import { request as __request } from '../core/request';
export class AccountingComptesService {
    /**
     * Get account by ID
     * @param id
     * @returns ApiResponseWrapperCompteDto OK
     * @throws ApiError
     */
    public static getCompteById(
        id: string,
    ): CancelablePromise<ApiResponseWrapperCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/{id}',
            path: {
                'id': id,
            },
        });
    }
    /**
     * Update an account
     * @param id
     * @param requestBody
     * @returns ApiResponseWrapperCompteDto OK
     * @throws ApiError
     */
    public static updateCompte(
        id: string,
        requestBody: CompteDto,
    ): CancelablePromise<ApiResponseWrapperCompteDto> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/accounting/comptes/{id}',
            path: {
                'id': id,
            },
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Delete an account
     * @param id
     * @returns ApiResponseWrapperString OK
     * @throws ApiError
     */
    public static deleteCompte(
        id: string,
    ): CancelablePromise<ApiResponseWrapperString> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/accounting/comptes/{id}',
            path: {
                'id': id,
            },
        });
    }
    /**
     * List all accounts
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static getAllComptes(): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes',
        });
    }
    /**
     * Create an accounting account
     * @param requestBody
     * @returns ApiResponseWrapperCompteDto OK
     * @throws ApiError
     */
    public static createCompte(
        requestBody: CompteDto,
    ): CancelablePromise<ApiResponseWrapperCompteDto> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/accounting/comptes',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Generate and create a Third-Party account
     * @param requestBody
     * @returns ApiResponseWrapperCompteDto OK
     * @throws ApiError
     */
    public static createAutoGeneratedAccount(
        requestBody: Record<string, string>,
    ): CancelablePromise<ApiResponseWrapperCompteDto> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/accounting/comptes/generate',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Search accounts by account number
     * @param noCompte
     * @returns ApiResponseWrapperListCompteDto OK
     * @throws ApiError
     */
    public static findByNoCompte(
        noCompte: string,
    ): CancelablePromise<ApiResponseWrapperListCompteDto> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/accounting/comptes/search',
            query: {
                'no_compte': noCompte,
            },
        });
    }
}
